# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    api_url: http://127.0.0.1/api/vouchers

services:
  partner:
    class: WebgearsBundle\External\Fetcher\Partner
    properties:
      api_url: "%api_url%"
  webgears_fetcher:
    class: WebgearsBundle\External\Fetcher
    arguments: ["@partner"]
  webgears_store:
    class: WebgearsBundle\Store\Store
    arguments: ["@doctrine.orm.entity_manager", "@logger"]
    tags:
      - { name: monolog.logger, channel: store }
